from selenium import webdriver

import time
driver = webdriver.Firefox()
driver.maximize_window()
time.sleep(3)
driver.get("https://google.com")
time.sleep(3)
driver.get("https://Apple.com")
time.sleep(3)
driver.back()
print(driver.title)
time.sleep(3)
driver.forward()
print(driver.title)
time.sleep(3)
driver.refresh()
print(driver.title)
time.sleep(3)
driver.close()
